### ISSUE TITLE
Please make hpack a working osgi bundle

### ISSUE THREAD

**Issue by CodingFabian** [twitter/hpack#22]
right now one cannot use hpack as osgi bundle and it has to be wrapped to be used. it would be nice if you could add the required headers to make it work out of the box.
This can be as simple as exporting "com.twitter.hpack.*"

One way of doing it would be a maven plugin like this:

      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.4.0</version>
        <executions>
          <execution>
            <id>generate-manifest</id>
            <phase>process-classes</phase>
            <goals>
              <goal>manifest</goal>
            </goals>
            <configuration>
              <supportedProjectTypes>
                <supportedProjectType>jar</supportedProjectType>
              </supportedProjectTypes>
              <instructions>
                <Export-Package>com.twitter.hpack.*</Export-Package>
              </instructions>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by jpinner** [comment]
@CodingFabian I've created a new branch (https://github.com/twitter/hpack/tree/osgi) that should create the necessary manifest file. Could you verify that the built jar works as expected.

Thanks!

**Comment by CodingFabian** [comment]
I can confirm that this is now a valid osgi bundle which declares that it exports `com.twitter.hpack`.

Before:
```
karaf@root()> bundle:headers 50

Bundle 50
---------
Archiver-Version = Plexus Archiver
Build-Jdk = 1.8.0_40
Built-By = fabian
Created-By = Apache Maven 3.2.5
Manifest-Version = 1.0
```

after

```
karaf@root()> bundle:headers 51

HPACK (51)
----------
Archiver-Version = Plexus Archiver
Bnd-LastModified = 1428340898646
Build-Jdk = 1.8.0_40
Built-By = fabian
Created-By = Apache Maven Bundle Plugin
Manifest-Version = 1.0
Tool = Bnd-2.3.0.201405100607

Bundle-Description = Header Compression for HTTP/2
Bundle-License = http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion = 2
Bundle-Name = HPACK
Bundle-SymbolicName = com.twitter.hpack
Bundle-Version = 0.10.2.SNAPSHOT

Require-Capability =
	osgi.ee;filter:=(&(osgi.ee=JavaSE)(version=1.6))

Export-Package =
	com.twitter.hpack;version=0.10.2
```
