### ISSUE TITLE
Benchmarks for hpack

### ISSUE THREAD

**Issue by nmittler** [twitter/hpack#23]
We've started [benchmarking the HTTP/2 implementation for Netty](https://github.com/netty/netty/tree/master/microbench/src/main/java/io/netty/microbench/http2) and I'd like to do something similar for hpack.  This will require some restructuring of the project, so that we can have submodules for "core" and "microbench" (since we won't want the benchmark code as part of the main jar).  Does this sound reasonable?  If so, I'll throw together a PR.

@jpinner 

/cc @Scottmitch @louiscryan @buchgr

**Comment by Scottmitch** [comment]
+1 for benchmarks

**Comment by jpinner** [comment]
@nmittler Sounds great. I've done some in the past using using caliper (testing things like the huffman decoding impl vs the table based approaches found in nghttp2 and grpc). For this I just put the code under the test directory but I'm open to any project structure that makes sense. PRs are always welcome.

**Comment by nmittler** [comment]
@jpinner cool, I'll throw together a PR... stay tuned!

Ideally I don't think we'd want the benchmarks under test, since they may take a while and we wouldn't want them to run whenever we build.

**Comment by jpinner** [comment]
@nmittler I think you can achieve that by creating a "benchmark" maven profile and only including the benchmark dependencies and executions in that profile.

**Comment by nmittler** [comment]
@jpinner Yeah that should work ... would that be your preference then?

**Comment by nmittler** [comment]
@jpinner if we had a separate module, however, we could also deploy a microbench jar.  Just a thought.

**Comment by jpinner** [comment]
I  know we went the sub-module route with Netty but I find them to be a bit of pain. If you want to build multiple jars you can still do this with profiles and customize the jars.

Honestly whatever you find to be the easiest is fine :)
